In [20]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [21]:
d=pd.read_csv('carprices.csv')
d

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [22]:
dm=pd.get_dummies(d['Car Model'])
dm

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [23]:
merge=pd.concat([dm,d],axis='columns')

In [24]:
merge

Audi A5  BMW X5  Mercedez Benz C class              Car Model  Mileage  \
0         0       1                      0                 BMW X5    69000   
1         0       1                      0                 BMW X5    35000   
2         0       1                      0                 BMW X5    57000   
3         0       1                      0                 BMW X5    22500   
4         0       1                      0                 BMW X5    46000   
5         1       0                      0                Audi A5    59000   
6         1       0                      0                Audi A5    52000   
7         1       0                      0                Audi A5    72000   
8         1       0                      0                Audi A5    91000   
9         0       0                      1  Mercedez Benz C class    67000   
10        0       0                      1  Mercedez Benz C class    83000   
11        0       0                      1  Mercedez Benz C class    79000   
12        0       0                      1  Mercedez Benz C class    59000   

    Sell Price($)  Age(yrs)  
0           18000         6  
1           34000         3  
2           26100         5  
3           40000         2  
4           31500         4  
5           29400         5  
6           32000         5  
7           19300         6  
8           12000         8  
9           22000         6  
10          20000         7  
11          21000         7  
12          33000         5

In [25]:

drp=merge.drop(['Mercedez Benz C class','Car Model'],axis='columns')
drp

Audi A5  BMW X5  Mileage  Sell Price($)  Age(yrs)
0         0       1    69000          18000         6
1         0       1    35000          34000         3
2         0       1    57000          26100         5
3         0       1    22500          40000         2
4         0       1    46000          31500         4
5         1       0    59000          29400         5
6         1       0    52000          32000         5
7         1       0    72000          19300         6
8         1       0    91000          12000         8
9         0       0    67000          22000         6
10        0       0    83000          20000         7
11        0       0    79000          21000         7
12        0       0    59000          33000         5

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
reg=LinearRegression()

In [28]:
reg

LinearRegression()

In [29]:
x=drp.drop(['Sell Price($)'],axis='columns')
y=drp['Sell Price($)']


In [30]:
reg.fit(x,y)

LinearRegression()

In [31]:
reg.predict([[1,0,53000,6]])

array([28911.89246304])

In [32]:
reg.score(x,y)

0.9417050937281083

In [33]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [34]:
le=LabelEncoder()
dfle=d

In [35]:
dfle['Car_Model'] = le.fit_transform(dfle['Car Model'])

In [36]:
dfle=dfle.drop(['Car Model'],axis='columns')

In [42]:
dfle

Mileage  Sell Price($)  Age(yrs)  Car_Model
0     69000          18000         6          1
1     35000          34000         3          1
2     57000          26100         5          1
3     22500          40000         2          1
4     46000          31500         4          1
5     59000          29400         5          0
6     52000          32000         5          0
7     72000          19300         6          0
8     91000          12000         8          0
9     67000          22000         6          2
10    83000          20000         7          2
11    79000          21000         7          2
12    59000          33000         5          2

In [74]:
X=dfle.drop(['Sell Price($)'],axis='columns').values
Y=dfle['Sell Price($)'].values
Y

array([18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000,
       22000, 20000, 21000, 33000], dtype=int64)

In [75]:
from sklearn.preprocessing import OneHotEncoder

In [80]:
oho=OneHotEncoder(categorical_features=[0])

TypeError: __init__() got an unexpected keyword argument 'categorical_features'

In [82]:
ohe.fit_transform(X).toarray()

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,

In [87]:
reg.fit(X,Y)

LinearRegression()

In [90]:
reg.predict([[0,4,45000]])

array([49624929.27836946])

In [91]:
reg.score(X,Y)

0.8719970367825952